name: Test_name_123

on:
  push:
    branches: 
      -master
  

jobs:
  testing_1111:
  
    runs-on: ubuntu-latest
    steps:
      - name: mesadge
        run: echo "hello world"


  testing_222:
  
    runs-on: ubuntu-latest
    steps:
      - name: mesadge_22
        run: echo "hello world  gay"
        
          


