name: Test

on:
  push:
    branches: 
      -master
  

jobs:
  testing_1:
  
    runs-on: ubuntu-latest
    steps:
      - name: mesadge
        run: echo "hello world"


  testing_2:
  
    runs-on: ubuntu-latest
    steps:
      - name: mesadge_22
        run: echo "hello world  gay"
        
          


