name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install dev tools
      run: |
        pip install mypy flake8 black pytest
        
        

    - name: Run flake8
      run: |
        flake8 app tests --count --show-source --statistics --max-line-length=88

    - name: Run black
      run: |        
        black --check --line-length 88 app tests
        
        

    - name: Run mypy with config
      run: |
        mypy --config-file=mypy.ini --exclude site-packages app/

    - name: Run tests
      run: |
        # Создаем тестовую БД и заполняем данными
        python -c "
        from app import create_app, db
        from app.models import Client, Parking
        from app.factories import ClientFactory, ParkingFactory
        app = create_app()
        with app.app_context():
            db.drop_all()
            db.create_all()
            for _ in range(5): db.session.add(ClientFactory())
            for _ in range(3): db.session.add(ParkingFactory())
            db.session.commit()
            print('Test data created')
        "
        pytest -v --tb=short --cov=app